package _11_transform_safeoperation_int_range.constraints;

import _11_transform_safeoperation_int_range.predicates.*;

/**
 * Constraint class of Integer.
 * <pre>IntEqualZero.</pre>
 * Generated by {@link _11_transform_safeoperation_int_range.TransformSafeOperationIntRangeConstraintCodeGenerator}.
 * Line-Number 0.
 */
public final class IntEqualZero
{
	/**
	 * Context object of type Integer.
	 */
	public final Integer value;

	/**
	 * Constructor.
	 * 
	 * @param value current context object
	 * @throws IllegalArgumentException if constraint violated
	 */
	public IntEqualZero(
			final Integer value )
	{
		if ( ! test( value ) )
		{
			throw new IllegalArgumentException( "constraint violation" );
		}
		this.value = value;
	}

	/**
	 * Test method.
	 * 
	 * @param value current context object
	 * @return constraint expression satisfied or not
	 */
	public static boolean test(
			final Integer value )
	{
		return new IntEqual( 0 ).test( value );
	}

	/**
	 * Convert this constraint type to a compatible type of this type.
	 * <pre>(IntGreaterZero or IntEqualZero).</pre>
	 * 
	 * @return compatible type of this type
	 */
	public ORB_IntGreaterZero_IntEqualZero_ORE convertToORB_IntGreaterZero_IntEqualZero_ORE()
	{
		return new ORB_IntGreaterZero_IntEqualZero_ORE(
				this.value );
	}

	/**
	 * Debug output.
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "IntEqualZero: " + this.value;
	}

}