package _10_transform_safeoperation_str_len.constraints;

import _10_transform_safeoperation_str_len.predicates.*;

/**
 * Constraint class of String.
 * <pre>StrExactLen15.</pre>
 * Generated by {@link _10_transform_safeoperation_str_len.TransformSafeOperationStrLenConstraintCodeGenerator}.
 * Line-Number 171.
 */
public final class StrExactLen15
{
	/**
	 * Context object of type String.
	 */
	public final String str;

	/**
	 * Constructor.
	 * 
	 * @param str current context object
	 * @throws IllegalArgumentException if constraint violated
	 */
	public StrExactLen15(
			final String str )
	{
		if ( ! test( str ) )
		{
			throw new IllegalArgumentException( "constraint violation" );
		}
		this.str = str;
	}

	/**
	 * Test method.
	 * 
	 * @param str current context object
	 * @return constraint expression satisfied or not
	 */
	public static boolean test(
			final String str )
	{
		return new StrExactLen( 15 ).test( str );
	}

	/**
	 * Convert this constraint type to a compatible type of this type.
	 * <pre>StrIsNotNull.</pre>
	 * 
	 * @return compatible type of this type
	 */
	public StrIsNotNullConstraint convertToStrIsNotNullConstraint()
	{
		return new StrIsNotNullConstraint(
				this.str );
	}

	/**
	 * Debug output.
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "StrExactLen15: " + this.str;
	}

}