package _06_switch_fizzbuzz.constraints;

import _06_switch_fizzbuzz.predicates.*;

/**
 * Constraint class of Integer.
 * <pre>(not(Fizz) and not(Buzz)).</pre>
 * Generated by {@link _06_switch_fizzbuzz.FizzBuzzConstraintCodeGenerator}.
 * Line-Number 149.
 */
public final class ANDB_NOT_Fizz_NOT_Buzz_ANDE
{
	/**
	 * Context object of type Integer.
	 */
	public final Integer value;

	/**
	 * Constructor.
	 * 
	 * @param value current context object
	 * @throws IllegalArgumentException if constraint violated
	 */
	public ANDB_NOT_Fizz_NOT_Buzz_ANDE(
			final Integer value )
	{
		if ( ! test( value ) )
		{
			throw new IllegalArgumentException( "constraint violation" );
		}
		this.value = value;
	}

	/**
	 * Test method.
	 * 
	 * @param value current context object
	 * @return constraint expression satisfied or not
	 */
	public static boolean test(
			final Integer value )
	{
		return ( ( ! new Fizz().test( value ) ) &&
					( ! new Buzz().test( value ) ) );
	}

	/**
	 * Debug output.
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "(not(Fizz) and not(Buzz)): " + this.value;	}

}