package _02_includes.constraints;

import _02_includes.enums.*;
import _02_includes.predicates.*;

/**
 * Constraint class of Rolle.
 * <pre>(RolleZentrale xor RolleNiederlassung).</pre>
 * Generated by {@link _02_includes.IncludesConstraintCodeGenerator}.
 * Line-Number 101.
 */
public final class XORB_RolleZentrale_RolleNiederlassung_XORE
{
	/**
	 * Context object of type Rolle.
	 */
	public final Rolle rolle;

	/**
	 * Constructor.
	 * 
	 * @param rolle current context object
	 * @throws IllegalArgumentException if constraint violated
	 */
	public XORB_RolleZentrale_RolleNiederlassung_XORE(
			final Rolle rolle )
	{
		if ( ! test( rolle ) )
		{
			throw new IllegalArgumentException( "constraint violation" );
		}
		this.rolle = rolle;
	}

	/**
	 * Test method.
	 * 
	 * @param rolle current context object
	 * @return constraint expression satisfied or not
	 */
	public static boolean test(
			final Rolle rolle )
	{
		return ( ( ( new RolleZentrale().test( rolle ) ? 1 : 0 ) +
					( new RolleNiederlassung().test( rolle ) ? 1 : 0 ) ) == 1 );
	}

	/**
	 * Debug output.
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "(RolleZentrale xor RolleNiederlassung): " + this.rolle;
	}

}