package _09_new_safeoperation_str_len.constraints;

import _09_new_safeoperation_str_len.predicates.*;

/**
 * Constraint class of String.
 * <pre>StrIsNotNull.</pre>
 * Generated by {@link _09_new_safeoperation_str_len.NewSafeOperationStrLenConstraintCodeGenerator}.
 * Line-Number 61.
 */
public final class StrIsNotNullConstraint
{
	/**
	 * Context object of type String.
	 */
	public final String str;

	/**
	 * Constructor.
	 * 
	 * @param str current context object
	 * @throws IllegalArgumentException if constraint violated
	 */
	public StrIsNotNullConstraint(
			final String str )
	{
		if ( ! test( str ) )
		{
			throw new IllegalArgumentException( "constraint violation" );
		}
		this.str = str;
	}

	/**
	 * Test method.
	 * 
	 * @param str current context object
	 * @return constraint expression satisfied or not
	 */
	public static boolean test(
			final String str )
	{
		return new StrIsNotNull().test( str );
	}

	/**
	 * Debug output.
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return "StrIsNotNull: " + this.str;
	}

}